### ISSUE TITLE
MODELO

### ISSUE THREAD

**Issue by mendezleon** [migueldiaz/mleon#11]
MIGUEL EN MODELO EL ALTO ANCHO Y FONDO NO LO HACE BIEN

**Comment by migueldiaz** [comment]
Solucionado, creo que te referías a cuando sale el listado , no?
Los modelos heredan las medidas del mueble base.
Miralo si está bien dale abajo al close and comment, lo que sea comentario

**Comment by mendezleon** [comment]
OK SOLUCIONADO
