### ISSUE TITLE
MUEBLE Y MODELO

### ISSUE THREAD

**Issue by mendezleon** [migueldiaz/mleon#12]
HAY UN MUEBLE QUE NO ME DEJA BORRAR Y TENGO QUE MODIFICAR Y EN EL DESGLOSE ME APARECEN PIEZA QUE NO SON

**Comment by migueldiaz** [comment]
El desglose no lo tengas en cuenta aun que queda trabajo.
Pone el nombre del mueble y lo miro

---

De: mendezleonmailto:notifications@github.com
Enviado: ‎20/‎01/‎2015 11:22
Para: migueldiaz/mleonmailto:mleon@noreply.github.com
Asunto: [mleon] MUEBLE Y MODELO (#12)

HAY UN MUEBLE QUE NO ME DEJA BORRAR Y TENGO QUE MODIFICAR Y EN EL DESGLOSE ME APARECEN PIEZA QUE NO SON

---

Reply to this email directly or view it on GitHub:
https://github.com/migueldiaz/mleon/issues/12

**Comment by migueldiaz** [comment]
Dejo esto abierto, cuando te vea intentamos replicar la situación a ver que es mejorable

**Comment by migueldiaz** [comment]
Da la impresión de que fuera algún dato huérfano durante el desarrollo.
No hemos podido replicar la situación, cierro y estamos atentos...
