### ISSUE TITLE
Visualizacion del desglose - DESGLOSE DE PEDIDO

### ISSUE THREAD

**Issue by mendezleon** [migueldiaz/mleon#13]
EN DESGLOSE DE PEDIDO HABRIA QUE PONER EN PESTAÑA DISTINTA PUERTA Y HERRAJE IGUAL QUE EN PIEZAS PARA IMPRIMIRLO POR SEPARADO

**Comment by migueldiaz** [comment]
Hecho, 
De todas formas aún queda pendiente agrupar las piezas, cuando liquide eso trabajo con la visualización del desglose, 
Se pueden poner páginas independientes y quiero ocultar la información que no se use para que el documento al imprimir quede mejor. 
Cierro issue y la renombro a 'Visualizacion del desglose' para reabrir más adelante
