### ISSUE TITLE
TIPO DE PIEZAS

### ISSUE THREAD

**Issue by mendezleon** [migueldiaz/mleon#14]
MIGUEL EN LAS PIEZA CUANDO LAS CREO SE PODRIA QUE SE ORDENARAN ALFABETICAMENTE?

**Comment by migueldiaz** [comment]
Sí se puede, en la siguiente fase, cuando confirmemos que los datos   se gestionan bien me centro en eso.
Mi idea es algo parecido a esto (bajando un poco la tabla que hay): http://www.datatables.net/

**Comment by migueldiaz** [comment]
Ordena alfabeticamente
